name: Fuzz Testing

on:
  workflow_dispatch:

permissions: read-all

jobs:
  fuzz:
    permissions:
      contents: read
    name: Run cargo-fuzz (Shard ${{ matrix.shard }}/8)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3, 4, 5, 6, 7, 8]

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install nightly Rust
        uses: dtolnay/rust-toolchain@5b842231ba77f5c045dba54ac5560fed2db780e2 # nightly

      - name: Install cargo-fuzz
        run: cargo install cargo-fuzz

      - name: Run fuzzer (audit_diff)
        run: cargo fuzz run fuzz_audit -- -max_total_time=300
