name: Kani Rust Verifier

on:
  workflow_dispatch:

permissions: read-all

jobs:
  kani:
    permissions:
      contents: read
    name: Run Kani Model Checking - ${{ matrix.package }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ['rullst-orm', 'rullst-orm-macros']

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Verify with Kani
        uses: model-checking/kani-github-action@f838096619a707b0f6b2118cf435eaccfa33e51f # v1.1
        with:
          args: --package ${{ matrix.package }}
