name: Kani Rust Verifier

on:
  workflow_dispatch:

permissions: read-all

jobs:
  kani:
    permissions:
      contents: read
    name: Run Kani Model Checking - ${{ matrix.package }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ['rullst-orm', 'rullst-orm-macros']

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Create Cargo Wrapper to Ignore MSRV
        run: |
          mv $HOME/.cargo/bin/cargo $HOME/.cargo/bin/cargo-real
          echo '#!/bin/bash' > $HOME/.cargo/bin/cargo
          echo 'CMD="$1"' >> $HOME/.cargo/bin/cargo
          echo 'if [[ "$CMD" == "build" || "$CMD" == "check" || "$CMD" == "rustc" || "$CMD" == "test" ]]; then' >> $HOME/.cargo/bin/cargo
          echo '    exec $HOME/.cargo/bin/cargo-real "$@" --ignore-rust-version' >> $HOME/.cargo/bin/cargo
          echo 'else' >> $HOME/.cargo/bin/cargo
          echo '    exec $HOME/.cargo/bin/cargo-real "$@"' >> $HOME/.cargo/bin/cargo
          echo 'fi' >> $HOME/.cargo/bin/cargo
          chmod +x $HOME/.cargo/bin/cargo

      - name: Verify with Kani
        uses: model-checking/kani-github-action@f838096619a707b0f6b2118cf435eaccfa33e51f # v1.1
        with:
          args: --package ${{ matrix.package }}
