name: Miri Memory Analysis

on:
  workflow_dispatch:

permissions: read-all

jobs:
  miri:
    permissions:
      contents: read
    name: Run Miri (Undefined Behavior Check) - ${{ matrix.package }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ['rullst-orm']

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Install Miri
        run: |
          rustup toolchain install nightly --component miri
          rustup default nightly
          cargo miri setup

      - name: Run Miri Tests
        run: MIRIFLAGS="-Zmiri-disable-isolation" cargo miri test -p ${{ matrix.package }} --lib
