name: Miri Memory Analysis

on:
  workflow_dispatch:

permissions: read-all

jobs:
  miri:
    permissions:
      contents: read
    name: Run Miri (Undefined Behavior Check) - ${{ matrix.package }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ['rullst-orm', 'rullst-orm-macros']

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Install Miri
        run: |
          rustup toolchain install nightly --component miri
          rustup default nightly
          cargo miri setup

      - name: Run Miri Tests
        run: MIRIFLAGS="-Zmiri-disable-isolation" cargo miri test -p ${{ matrix.package }}
